### ISSUE TITLE
What is the "correct head"?

### ISSUE THREAD

**Issue by BUGHUNTER** [xrg/OpenERP#1]
Hi, first thank you very much for this mirror! 

I do not not understand the instructions and have a few questions:

"Checkout the correct head (ask inside for details)."

What is the "correct head"? How do I get this information?
Could you show an example of how to check out the actual sources for 6.1?

Also: how often is this updated? 
Is this automatically mirrored?

Thank you very much for your attention!

**Comment by xrg** [comment]
Hello. You know, there is no standard way in git to have a repo-wide Readme file (not dependant on the branch you are looking at). So, I wrote a few words in github's wiki pages FYI.

[ if you haven't read about git-submodules, please do now... ]

This repo does not technically "contain" the full sources, but instructions how to clone the ones. And, commits here are mere "snapshots" of the commits I've tested each time.
So, for all "addons", "server", "client" etc. I'm syncing with LP every day, every hour. Once you clone these, you should have all 5.0, 6.0, 6.1, trunk, xrg and F3 series taking up your disk space!

Since I'm not involved or interested in >=6.1, however, you'd need to checkout each of the submodules at these heads yourself. Say, 'cd' to each one and 'git checkout origin/official-6.1' for example. Then, you have the sources.

Regards.
